apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  replicas: 1  # prd environment uses 1 replica
  template:
    spec:
      containers:
        - name: hello-app
          image: nginx:latest
