apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
      <body>
        <pre>
        Hello, world!
        Version: 2.0.0 (prd)
        </pre>
      </body>
    </html>