apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stg
resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patch-configmap.yaml
  - path: patch-deployment.yaml
  - path: patch-service.yaml