apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: int-hello-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/hello-app/overlays/int
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: int
  timeout: 2m
  wait: true
