apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prd-hello-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/hello-app/overlays/prd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: prd
  timeout: 2m
  wait: true
